name: "version"
description: "Append pre-release version identifier to Cargo.toml"

inputs:
  platform:
    required: true
    description: "Runner platform"
  build-number:
    required: true
    description: "Monotonic nightly build number"
  tauri-config:
    required: false
    default: src-tauri/tauri.conf.json
    description: "Tauri config file"

outputs:
  date:
    description: "Human-readable date for use in releases"
    value: ${{ steps.version.outputs.date }}

runs:
  using: "composite"
  steps:
    - name: Get current date and version
      id: version
      shell: bash
      run: |
        # gets the date for both tag and version, and in human readable form for releases
        TAURI_CONF=${{ inputs.tauri-config }}
        DATE="$(date '+%Y-%m-%d')"
        VER=$(jq -r '.version' "$TAURI_CONF")
        BUILD_NUMBER=${{ inputs.build-number }}

        echo "date=$DATE" >> $GITHUB_OUTPUT
        echo "version=$VER" >> $GITHUB_OUTPUT

    - name: Patch product name for nightly
      shell: bash
      run: |
        TAURI_CONF=${{ inputs.tauri-config }}
        jq '.productName += " Nightly"' "$TAURI_CONF" > tmp.json && mv tmp.json "$TAURI_CONF"

    - name: Patch version in Cargo.toml for nightly (Ubuntu & MacOS)
      if: inputs.platform != 'windows-latest'
      shell: bash
      run: |
        TAURI_CONF=${{ inputs.tauri-config }}
        VER="${{ steps.version.outputs.version }}-nightly.${{ inputs.build-number }}"
        jq --arg v "$VER" '.version = $v' "$TAURI_CONF" > tmp.json && mv tmp.json "$TAURI_CONF"

    - name: Patch version in Cargo.toml for nightly (Windows)
      if: inputs.platform == 'windows-latest'
      shell: bash
      run: |
        TAURI_CONF=${{ inputs.tauri-config }}
        VER="${{ steps.version.outputs.version }}.${{ inputs.build-number }}"
        jq --arg v "$VER" '.version = $v' "$TAURI_CONF" > tmp.json && mv tmp.json "$TAURI_CONF"

    - name: Log patched nightly version
      shell: bash
      run: |
        PATCHED_VERSION=$(cargo metadata --frozen --no-deps --color never --format-version 1 --manifest-path src-tauri/Cargo.toml | jq -r '.packages[0].version')
        PRODUCT_NAME=$(jq -r '.productName' src-tauri/tauri.conf.json)
        echo "Nightly version: $PATCHED_VERSION"
        echo "Product name: $PRODUCT_NAME"
