name: "Build and test on PR"

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "src/**"
      - "src-tauri/**"
      - "index.html"
      - "package.json"
      - "pnpm-lock.json"
      - "tsconfig.json"
      - "vite.config.ts"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest"
            args: "--target aarch64-apple-darwin"
          - platform: "ubuntu-22.04"
            args: ""
          - platform: "windows-latest"
            args: ""

    uses: ./.github/workflows/tauri-build.yaml
    secrets: inherit
    with:
      platform: ${{ matrix.platform }}
      args: ${{ matrix.args }}
