name: 'nightly'
description: 'Create a nightly build'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
      timezone: 'Europe/Istanbul'

jobs:
  check-for-changes:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.detect-changes.outputs.changed }}
    steps:
      - uses: actions/checkout@v6

      - name: check for changes
        id: detect-changes
        run: |
          if git log --since="24 hours ago" --oneline | grep -q .; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

  nightly:
    needs: check-for-changes
    if: needs.check-for-changes.outputs.changed == 'true'

    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            args: '--target aarch64-apple-darwin'
          - platform: 'ubuntu-22.04'
            args: ''
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v6

      - name: get current date
        id: date
        shell: bash
        run: |
          # gets the date for both tag and version, and in human readable form for releases
          echo "date=$(date '+%Y%m%d')" >> $GITHUB_OUTPUT
          echo "date-hr=$(date '+%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: patch nightly version
        shell: bash
        run: |
          DATE="${{ steps.date.outputs.date }}"
          VER=$(jq -r '.version' src-tauri/tauri.conf.json)
          NIGHTLY_VER="${VER}-nightly.${{ steps.date.outputs.date }}"

          JSON_FILES=(src-tauri/tauri.conf.json package.json)
          TOML_FILES=(src-tauri/Cargo.toml)

          for f in "${JSON_FILES[@]}"; do
            echo "Patching $f"
            jq --arg v "$NIGHTLY_VER" '.version = $v' "$f" > tmp.json && mv -v tmp.json "$f"
          done

          for f in "${JSON_FILES[@]}"; do
            echo "Patching $f"
            sed -i "s/^version = \".*\"/version = \"$NIGHTLY_VER\"/" "$f"
          done

          jq --arg -v "$NIGHTLY_VER" '.version = $v' src-tauri/tauri.conf.json > tmp.json && mv -v tmp.json src-tauri/tauri.conf.json

      - uses: ./.github/actions/setup
        with:
          platform: ${{ matrix.platform }}

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: nightly-${{ steps.date.outputs.date }}
          releaseName: 'Quark Nightly ${{ steps.date.outputs.date-hr }}'
          releaseBody: 'Automated nightly build from main'
          releaseDraft: false
          prerelease: true
          generateReleaseNotes: false
          args: ${{ matrix.args }}

