name: "Publish - MacOS ARM"

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  macos-aarch64:
    secrets: inherit
    uses: ./.github/workflows/publish.yaml
    with:
      platform: macos-latest
      args: "--target aarch64-apple-darwin"
