name: "Publish - Common"

on:
  workflow_call:
    inputs:
      platform:
        type: string
        required: true
        description: "Target platform to publish on"
      args:
        type: string
        required: false
        description: "Additional arguments passed to tauri-action"
        default: ""

jobs:
  prepare:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/check-version
        with:
          version: ${{ github.ref_name }}

  publish:
    needs: prepare

    permissions:
      contents: write

    uses: ./.github/workflows/tauri-build.yaml
    secrets: inherit
    with:
      platform: ${{ inputs.platform }}
      args: ${{ inputs.args }}
      tagName: v__VERSION__
      releaseName: "Quark v__VERSION__"
      releaseBody: "See the assets to download this version and install"
      generateReleaseNotes: true
