name: "Release"

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  prepare:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/check-version
        with:
          version: ${{ github.ref_name }}

  release:
    needs: prepare

    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest"
            args: "--target aarch64-apple-darwin"
            status-target: "macos-aarch64"
          - platform: "ubuntu-22.04"
            args: ""
            status-target: "linux"
          - platform: "windows-latest"
            args: ""
            status-target: "windows"

    permissions:
      contents: write

    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      badge_gist_token: ${{ secrets.BADGE_GIST_TOKEN }}
      badge_gist_id: ${{ secrets.BADGE_GIST_ID }}
      apple_api_key_id: ${{ secrets.APPLE_API_KEY_ID }}
      apple_api_issuer: ${{ secrets.APPLE_API_ISSUER }}
      apple_api_key: ${{ secrets.APPLE_API_KEY }}
      apple_certificate: ${{ secrets.APPLE_CERTIFICATE }}
      apple_certificate_password: ${{ secrets.APPLE_CERTIFICATE_PASS }}
      apple_keychain_password: ${{ secrets.KEYCHAIN_PASSWORD }}

    uses: ./.github/workflows/tauri-build.yaml
    with:
      platform: ${{ matrix.platform }}
      status-target: ${{ matrix.status-target }}
      args: ${{ matrix.args }}
      tagName: v__VERSION__
      releaseName: "Quark v__VERSION__"
      releaseBody: "See the assets to download this version and install"
      generateReleaseNotes: true
